#ifndef kibitz_router_hpp
#define kibitz_router_hpp

#include <kibitz/locator/common.hpp>
#include <kibitz/validator/validator.hpp>

using kibitz::graph::worker_graph_ptr;

namespace kibitz {
  namespace locator {

  /// \brief Listens for collaboration messages and distributes them to child workers.
  ///
  class router {
  public:
    /// c'tor
    /// 
    /// \param listener_binding ZMQ binding string for socket that will listen for inbound
    ///                         messages from workers.
    /// \param bindings bindings for outbound messages, these are generated by the create_bindings function
    /// \param graph_ptr contains collaboration graph information used to route messages
    ///
    router(const string& listener_binding, 
	   const binding_map_t& bindings, 
	   worker_graph_ptr graph_ptr  );
    ~router() ;

    void operator()() ;
  }; 
  }
}


#endif
