#!/usr/bin/env ruby

puts "Working dir #{ Dir.pwd }"

infile = ARGV.shift

inguids = IO.readlines( infile ).map { | guid | guid.chomp }


ARGV.each do | outfile | 
  outguid = IO.read( outfile ).chomp
  exit 1 unless inguids.index( outguid ) 
end


exit 0
